version: '3'
services:
  #PHP Service
  php:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: php:fpm-alpine
    container_name: php
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: php
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - php-network
 
  #MySQL Service
  db:
    image: percona:latest
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: db
    networks:
      - php-network
  #Nginx Service
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx/:/etc/nginx/conf.d/
    networks:
      - php-network
    depends_on:
      - php
      - db
#Docker Networks
networks:
  php-network:
    driver: bridge