version: '3'
services:
  #PHP Service
  php-library:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:7.4.5
    container_name: php-library
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: php-library
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - php-library-network

  #Nginx Service
  php-library-webserver:
    image: nginx:alpine
    container_name: php-library-webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8001:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - php-library-network
    depends_on:
      - php-library
      - php-library-db
 
  #MySQL Service
  php-library-db:
    image: percona:latest
    container_name: php-library-db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: php-library-db
    networks:
      - php-library-network

#Docker Networks
networks:
  php-library-network:
    driver: bridge